Set WshShell=Wscript.CreateObject("Wscript.Shell")
WshShell.SendKeys("[")
WScript.Sleep(1000)
WshShell.SendKeys("[")
WScript.Sleep(1000)
WshShell.SendKeys("[")
WScript.Sleep(1000)
WshShell.SendKeys("1")
WScript.Sleep(2000)
